### PR TITLE
list fields will now return `None` if the tag does not exist

### LINKED ISSUE #63: List fields don't return None if the tag doesn't exist
If a list tag does not exist, it returns an empty list rather than `None`, but if a non-list tag does not exist, `None` is returned.

I believe non-existent list tags should also return `None` so that this behavior is consistent.

### PR DESCRIPTION
**Pull request by jtpavlock**
Fixes #63

### CODE REVIEW

**Comment by jtpavlock** [comment]
I'm a bit confused on the tests concerning the wav bitrate. It seems different python versions are returning different results? Inspecting the test wav file in Windows seems to confirm the 705600 bitrate

**Comment by jtpavlock** [comment]
@sampsyo I know you're busy, but is there anything else I can do to help get this reviewed/merged?

**Review by sampsyo — APPROVED** [review]
Thank you for your patience!! This all looks good from here.

**Comment by jtpavlock** [comment]
Thanks for merging this in! Any chance you could cut a release with this fix?

**Comment by sampsyo** [comment]
Done! https://pypi.org/project/mediafile/

**Pull request merged**
