### PR TITLE
Added barcode field

### PR DESCRIPTION
**Pull request by SimonHova**
I added the barcode field to clear issue #26.

### CODE REVIEW

**Comment by sampsyo** [comment]
Looks great so far! We'll need to do a couple of things:

- Update the tests to include the new field.
- Double-check the new tag mappings against existing software, especially the [Picard tag mappings](https://picard.musicbrainz.org/docs/mappings/).

**Comment by sampsyo** [comment]
Looks great so far! We'll need to do a couple of things:

- Update the tests to include the new field.
- Double-check the new tag mappings against existing software, especially the [Picard tag mappings](https://picard.musicbrainz.org/docs/mappings/).

**Comment by SimonHova** [comment]
The tag mappings look pretty straightforward, with the exception of the iTunes. But, I matched with another field, and it looks good now. Tell me what you think.

**Comment by sampsyo** [comment]
Looks pretty good to me, and it seems to match the Picard mappings! Can you elaborate on what was less straightforward about the iTunes (MPEG-4) tag?

**Comment by SimonHova** [comment]
Sure. All the other tags had the name _barcode,_ but the iTunes one had six dashes instead. I'm presuming that means that iTunes doesn't support the field, but I copied the format which had an identical format from another field, so I'm confident that it's correct.

**Comment by sampsyo** [comment]
Just checking, do you mean *four* dashes, as in `----:com.apple.iTunes:BARCODE`? That is indeed what Picard seems to use, which is a good indication that it's also what other software uses. (It's worth mentioning that compatibility with other software is the paramount concern.)

**Comment by SimonHova** [comment]
That is absolutely correct, I copied the format from another field that had a similar notation in the table.

**Comment by sampsyo** [comment]
Perfect; thanks!! Merged. :sparkles:

**Pull request merged**
